apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-5yuv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-5yuv
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-5yuv
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-5yuv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-5yuv
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ncfk-tenant/rhtap-demo-app/hacbs-test-project-5yuv@sha256:5a9026d2c2c0649eca1c76421476e32b7d44dfd4241a5da9768d9e48d59f9ce9
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
