apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-5yuv
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ncfk-tenant/rhtap-demo-app/hacbs-test-project-5yuv@sha256:5a9026d2c2c0649eca1c76421476e32b7d44dfd4241a5da9768d9e48d59f9ce9
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
